name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: apt-update
      run: sudo apt-get update
    - name: install build tool
      run: sudo apt-get install gcc-arm-none-eabi python3-pip
    - name: pre build
      run: git submodule update --init --recursive --depth=1
    - name: install python dependencies
      run: python3 -m pip install crcmod
    - name: make
      run: make
    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: |
          bin/firmware.bin
          bin/firmware
